// refactored seed method to findOrCreate ingredient models; just keeping spices/seasonings in seed file for now
const ingredients = [
    {name: 'fresh basil', isSpice: 'true'},
    {name: 'salt', isSpice: 'true'},
    {name: 'pepper', isSpice: 'true'},
    {name: 'taco seasoning', isSpice: 'true'},
    // adding more in alphabetical order
    {name: 'allspice', isSpice: 'true'},
    {name: 'anise', isSpice: 'true'},
    {name: 'bay leaf', isSpice: 'true'},
    {name: 'cayenne pepper', isSpice: 'true'},
    {name: 'celery seed', isSpice: 'true'},
    {name: 'chili pepper', isSpice: 'true'},
    {name: 'chili powder', isSpice: 'true'},
    {name: 'cilantro', isSpice: 'true'},
    {name: 'cinnamon', isSpice: 'true'},
    {name: 'clove', isSpice: 'true'},
    {name: 'coriander', isSpice: 'true'},
    {name: 'cumin', isSpice: 'true'},
    {name: 'dill', isSpice: 'true'},
    {name: 'dried basil', isSpice: 'true'},
    {name: 'fennel', isSpice: 'true'},
    {name: 'fennel seeds', isSpice: 'true'},
    {name: 'ginger', isSpice: 'true'},
    {name: 'ground ginger', isSpice: 'true'},
    {name: 'horseradish', isSpice: 'true'},
    {name: 'Italian seasoning', isSpice: 'true'},
    {name: 'lemon grass', isSpice: 'true'},
    {name: 'marjoram', isSpice: 'true'},
    {name: 'nutmeg', isSpice: 'true'},
    {name: 'oregano', isSpice: 'true'},
    {name: 'fresh oregano', isSpice: 'true'},
    {name: 'paprika', isSpice: 'true'},
    {name: 'parsley', isSpice: 'true'},
    {name: 'fresh parsley', isSpice: 'true'},
    {name: 'rosemary', isSpice: 'true'},
    {name: 'saffron', isSpice: 'true'},
    {name: 'sage', isSpice: 'true'},
    {name: 'savory', isSpice: 'true'},
    {name: 'sesame', isSpice: 'true'},
    {name: 'tarragon', isSpice: 'true'},
    {name: 'thyme', isSpice: 'true'},
    {name: 'turmeric', isSpice: 'true'},
    {name: 'vanilla', isSpice: 'true'},
    {name: 'wasabi', isSpice: 'true'},
    {name: 'mustard powder', isSpice: 'true'},
    {name: 'red pepper flakes', isSpice: 'true'},
    {name: 'garlic powder', isSpice: 'true'},
    {name: 'onion powder', isSpice: 'true'},
    {name: 'file powder', isSpice: 'true'},
    {name: 'lemon pepper', isSpice: 'true'},
    {name: 'ancho chile pepper', isSpice: 'true'},
    {name: 'ground chipotle pepper', isSpice: 'true'},
    {name: 'cajun seasoning', isSpice: 'true'},
    {name: 'curry powder', isSpice: 'true'},
    {name: 'tandoori masala', isSpice: 'true'},
    {name: 'garam masala', isSpice: 'true'},
]

module.exports = ingredients;