// refactored seed method to findOrCreate ingredient models; just keeping spices/seasonings in seed file for now
const ingredients = [
    {name: 'fresh basil', isSpice: 'true'},
    {name: 'salt', isSpice: 'true'},
    {name: 'pepper', isSpice: 'true'},
    {name: 'taco seasoning', isSpice: 'true'},
    // adding more in alphabetical order
    {name: 'allspice', isSpice: 'true'},
    {name: 'anise', isSpice: 'true'},
    {name: 'bay leaf', isSpice: 'true'},
    {name: 'cayenne pepper', isSpice: 'true'},
    {name: 'chili pepper', isSpice: 'true'},
    {name: 'cilantro', isSpice: 'true'},
    {name: 'cinnamon', isSpice: 'true'},
    {name: 'clove', isSpice: 'true'},
    {name: 'coriander', isSpice: 'true'},
    {name: 'cumin', isSpice: 'true'},
    {name: 'dill', isSpice: 'true'},
    {name: 'fennel', isSpice: 'true'},
    {name: 'ginger', isSpice: 'true'},
    {name: 'horseradish', isSpice: 'true'},
    {name: 'lemon grass', isSpice: 'true'},
    {name: 'marjoram', isSpice: 'true'},
    {name: 'nutmeg', isSpice: 'true'},
    {name: 'oregano', isSpice: 'true'},
    {name: 'paprika', isSpice: 'true'},
    {name: 'parsley', isSpice: 'true'},
    {name: 'rosemary', isSpice: 'true'},
    {name: 'saffron', isSpice: 'true'},
    {name: 'sage', isSpice: 'true'},
    {name: 'savory', isSpice: 'true'},
    {name: 'sesame', isSpice: 'true'},
    {name: 'tarragon', isSpice: 'true'},
    {name: 'thyme', isSpice: 'true'},
    {name: 'turmeric', isSpice: 'true'},
    {name: 'vanilla', isSpice: 'true'},
    {name: 'wasabi', isSpice: 'true'},
    {name: 'mustard seed', isSpice: 'true'},
    {name: 'red pepper flakes', isSpice: 'true'}
]

module.exports = ingredients;